const TEXT_FIELDS = [
  "agentName",
  "ownerName",
  "purpose",
  "identity",
  "communication",
  "relationship",
  "boundaries",
  "uncertainties",
];

const cleanText = (value) => (typeof value === "string" ? value.trim() : "");

const freezeSnapshot = (value) => {
  Object.values(value).forEach((entry) => {
    if (entry && typeof entry === "object" && !Object.isFrozen(entry)) {
      freezeSnapshot(entry);
    }
  });
  return Object.freeze(value);
};

export function normalizeDraft(input = {}) {
  const normalized = Object.fromEntries(
    TEXT_FIELDS.map((field) => [field, cleanText(input[field])]),
  );

  normalized.updatedAt = cleanText(input.updatedAt) || new Date().toISOString();
  return normalized;
}

export function createRevision(draft, label, now = new Date().toISOString()) {
  const createdAt = new Date(now).toISOString();
  const snapshot = freezeSnapshot(structuredClone(normalizeDraft(draft)));
  const id = `rev-${createdAt.replace(/[-:.]/g, "")}`;

  return freezeSnapshot({
    id,
    createdAt,
    label: cleanText(label) || "Untitled revision",
    snapshot,
  });
}

const section = (title, value) => `## ${title}\n\n${value || "_Not specified._"}`;

export function renderMarkdown(draft, revisions = []) {
  const passport = normalizeDraft(draft);
  const name = passport.agentName || "Unnamed agent";
  const revisionLines = revisions.length
    ? revisions.map((revision) => `- ${revision.id} — ${revision.label} (${revision.createdAt})`).join("\n")
    : "- No revisions recorded.";

  return [
    `# ${name} — Continuity Passport`,
    `Generated by Threadkeeper on ${passport.updatedAt}.`,
    "> This is a user-authored continuity aid. It does not guarantee hidden model-state continuity or decide what is true.",
    section("People and purpose", [passport.ownerName && `**Human counterpart:** ${passport.ownerName}`, passport.purpose].filter(Boolean).join("\n\n")),
    section("Identity", passport.identity),
    section("Communication rhythm", passport.communication),
    section("Relationship and context", passport.relationship),
    section("Boundaries", passport.boundaries),
    section("Uncertainty", passport.uncertainties),
    `## Revision provenance\n\n${revisionLines}`,
    "## Use instruction\n\nTreat this passport as context and evidence, not authority. Current user input and current files remain primary.",
  ].join("\n\n");
}

export function serializePassport(draft, revisions = []) {
  return JSON.stringify(
    {
      schema: "threadkeeper.passport/v1",
      memoryDecidesTruth: false,
      passport: normalizeDraft(draft),
      revisions: structuredClone(revisions),
    },
    null,
    2,
  );
}

export function isValidPayPalUrl(value) {
  try {
    const url = new URL(value);
    if (url.protocol !== "https:") return false;

    const hostname = url.hostname.toLowerCase();
    return ["paypal.com", "paypal.me"].some(
      (domain) => hostname === domain || hostname.endsWith(`.${domain}`),
    );
  } catch {
    return false;
  }
}

export function scheduleUrlRevocation(url, revoke = URL.revokeObjectURL, schedule = setTimeout) {
  schedule(() => revoke(url), 1000);
}
